version: '3.9'

services:
  api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
    networks:
      - cab-pool-network

  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    networks:
      - cab-pool-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - cab-pool-network

networks:
  cab-pool-network:
    driver: bridge
