apiVersion: apps/v1
kind: Deployment
metadata:
  name: cabpool-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cabpool-backend
  template:
    metadata:
      labels:
        app: cabpool-backend
    spec:
      containers:
        - name: backend
          image: bambo0st/backend:latest
          imagePullPolicy: Always  
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: cabpool-secrets
                  key: mongo_url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cabpool-secrets
                  key: jwt_secret
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

