apiVersion: v1
kind: Service
metadata:
  name: cabpool-frontend-service
spec:
  selector:
    app: cabpool-frontend
  ports:
    - protocol: TCP
      port: 4173
      targetPort: 4173
      nodePort: 30000  
  type: NodePort
