---
# tasks/main.yml

- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes
  become: true
  # become_user: root

- name: Ensure Docker service is started and enabled
  service:
    name: docker
    state: started
    enabled: true
  become: true
  # become_user: root


